--> Q1 - What is the total number of rows in each of the 3tables in the database ?
SELECT COUNT(*) 
FROM CUSTOMER
UNION 
SELECT COUNT(*)
FROM PROD_CAT_INFO
UNION 
SELECT COUNT(*)
FROM TRANSACTIONS

-->Q2 - WHAT IS THE TOTAL NO OF TRANSACTIONS THAT HAVE A RETURN ?

--SELECT COUNT (*) AS TRA
--FROM TRANSACTIONS

SELECT COUNT (*) AS N0_OF_RETURN
FROM TRANSACTIONS
WHERE TOTAL_AMT < '0'


-->Q3- As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.

SELECT CONVERT(DATETIME,TRAN_DATE, 103)
FROM Transactions


-->Q4 What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.

SELECT DATEDIFF(DD,MIN(tran_date),MAX(TRAN_DATE)) AS DAYS_,
	DATEDIFF(MM,MIN(tran_date),MAX(TRAN_DATE)) AS MONTHS,
	DATEDIFF(YY,MIN(tran_date),MAX(TRAN_DATE)) AS YEARS

FROM Transactions


-->Q5 Which product category does the sub-category “DIY” belong to?

select prod_cat
from prod_cat_info
where prod_subcat like 'DIY'

-- DATA ANALYSIS
-->Q1 - 
SELECT TOP 1 STORE_TYPE
FROM 
(
SELECT
STORE_TYPE,COUNT(STORE_TYPE) AS COUNTS
FROM TRANSACTIONS
GROUP BY STORE_TYPE
)AS X
ORDER BY COUNTS DESC

-->Q2 -
SELECT GENDER,COUNT(Customer_ID) as COUNTG
FROM CUSTOMER
WHERE GENDER IN('M','F')
GROUP BY GENDER

-->Q3- From which city do we have the maximum number of customers and how many?

SELECT TOP 1
CITY_CODE,COUNT(CUSTOMER_ID) AS COUNTCT
FROM CUSTOMER
GROUP BY CITY_CODE
ORDER BY COUNTCT DESC

-->Q4- How many sub-categories are there under the Books category?

SELECT COUNT (PROD_SUBCAT) AS SUBCAT_CNT
FROM prod_cat_info
where prod_cat = 'BOOKS'
group by prod_cat

-->Q5- What is the maximum quantity of products ever ordered?

SELECT TOP 1 QTY
FROM TRANSACTIONS
ORDER BY QTY DESC

-->Q6- What is the net total revenue generated in categories Electronics and Books?

select SUM(CAST(total_amt AS float)) AS TOTAL_REVENUE,prod_cat
from Transactions as A
INNER JOIN prod_cat_info AS B
ON A.prod_cat_code =B.prod_cat_code
WHERE PROD_CAT IN ('Books','Electronics')
group by prod_cat

-->Q7 - How many customers have >10 transactions with us, excluding returns?
SELECT COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT
FROM CUSTOMER WHERE customer_Id IN
(
SELECT CUST_ID
FROM Transactions
LEFT JOIN Customer ON customer_Id = cust_id
WHERE total_amt NOT LIKE '-%'
GROUP BY cust_id
HAVING COUNT(Transaction_ID)>10
)

-->Q8 - What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT SUM(CAST(TOTAL_AMT AS float))AS TOTAL_REVENUE,Store_type
FROM Transactions AS A
LEFT JOIN prod_cat_info AS B
ON A.prod_cat_code = B.prod_cat_code
WHERE prod_cat IN ('ELECTRONICS' , 'CLOTHING')
GROUP BY Store_type
HAVING Store_type= 'FLAGSHIP STORE'

-->Q9 - What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT prod_subcat as sub_cat, SUM(CAST(TOTAL_AMT AS FLOAT)) AS TTL_REVENUE
FROM Transactions
LEFT JOIN Customer
	on Transactions.cust_id = customer.customer_Id
LEFT JOIN[prod_cat_info]
	on [Transactions].[prod_cat_code] = [prod_cat_info] . [prod_cat_code]

where Gender like 'M' and prod_cat in ('Electronics')
group by [prod_subcat]


-->Q10 - What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
select Top(5) p.prod_subcat , sum(cast(total_amt as float))/(select sum(cast(total_amt as float)) from Transactions)*100 as sales
from transactions t
inner join prod_cat_info p
on p.prod_cat_code = t.prod_cat_code
and p.prod_sub_cat_code = t.prod_subcat_code
group by p.prod_subcat
order by sales desc


--> Q11- For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

select sum(Convert(numeric, total_amt ))as net_total_revenue
FROM Customer c
left join  
Transactions t
on c.customer_Id = t.cust_id
where datediff(year,dob,getdate())>=25
and
datediff (year,dob,getdate())>=35
and datediff(day,tran_date,'2014-02-28') <=30



-->Q12 - Which product category has seen the max value of returns in the last 3 months of transactions?

 select top 1 prod_cat from(
							select prod_cat , sum(convert(numeric, total_amt))as value_return
							from prod_cat_info p
							left join Transactions t
							on p.prod_cat_code = t.prod_cat_code
							where DATEDIFF(month,tran_date,'2014-02-28')<=3
							and convert(numeric,QTY)<0
							group by prod_cat) as A
 order by value_return


-->Q13 - Which store-type sells the maximum products; by value of sales amount and by quantity sold?

select TOP 1 STORE_TYPE FROM(
SELECT STORE_TYPE, SUM(CONVERT(numeric,total_amt)) AS SALE_AMT, SUM(CONVERT(NUMERIC,QTY )) AS SUM_QTY
FROM Transactions
GROUP BY Store_type) AS Q
ORDER BY SALE_AMT DESC, SUM_QTY DESC

--Q14- What are the categories for which average revenue is above the overall average ?
SELECT AVG(CAST(TOTAL_AMT AS float)) AS AVG_REVENUE , PROD_CAT_CODE
FROM Transactions
GROUP BY prod_cat_code
HAVING AVG(CAST(TOTAL_AMT AS float)) >(SELECT(AVG(CAST(TOTAL_AMT AS FLOAT))) FROM Transactions)

-->Q15- Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold ?

select top(5)prod_cat, prod_subcat, average_revenue, total_revenue from
(
select prod_subcat,prod_cat,
avg(convert(numeric,total_amt)) as average_revenue,
sum(convert(numeric,total_amt)) as total_revenue,
sum(convert(numeric,qty)) as sumqty
from prod_cat_info
left join Transactions
on prod_cat_info.prod_sub_cat_code = Transactions.prod_subcat_code and prod_cat_info.prod_cat_code=transactions.prod_cat_code
group by prod_subcat,prod_cat
) as p
order by sumqty desc 




